// Well-known Indian real-estate developers / builders.
// Used to power the builder-name autocomplete in the project wizard and the
// public "List Property" form. Free text is still allowed for builders not
// on the list.
export const INDIAN_BUILDERS: string[] = [
  "DLF",
  "Godrej Properties",
  "Lodha Group (Macrotech)",
  "Prestige Group",
  "Oberoi Realty",
  "Brigade Group",
  "Sobha Limited",
  "Tata Housing",
  "Mahindra Lifespaces",
  "Sunteck Realty",
  "Hiranandani Group",
  "Kalpataru Group",
  "Puravankara",
  "Shapoorji Pallonji Real Estate",
  "Raymond Realty",
  "Adani Realty",
  "Birla Estates",
  "Ashiana Housing",
  "Gaurs Group",
  "ATS Infrastructure",
  "Supertech",
  "Jaypee Greens",
  "Amrapali Group",
  "Eldeco Group",
  "Migsun Group",
  "Ace Group",
  "Mahagun Group",
  "Nirala World",
  "County Group",
  "VVIP Group",
  "Irish Developers",
  "Skyline Infratech",
  "Paras Buildtech",
  "Bhutani Infra",
  "Wave Group",
  "Logix Group",
  "M3M India",
  "Signature Global",
  "Emaar India",
  "Experion Developers",
  "Vatika Group",
  "Central Park",
  "Ireo",
  "Unitech",
  "Omaxe",
  "Ansal API",
  "Assetz Property Group",
  "Embassy Group",
  "Total Environment",
  "Rohan Builders",
  "Kolte-Patil Developers",
  "Gera Developments",
  "Nyati Group",
  "Casagrand",
  "Purva (Provident Housing)",
  "Salarpuria Sattva",
  "My Home Group",
  "Aparna Constructions",
  "Phoenix Mills",
  "Runwal Group",
  "Wadhwa Group",
  "Rustomjee",
  "Piramal Realty",
  "K Raheja Corp",
];
